# Generated by Django 3.2.25 on 2025-07-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('Buick', 'Buick'), ('Chevrolet', 'Chevrolet'), ('Cadillac', 'Cadillac'), ('GMC', 'GMC')], max_length=20)),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
